config/routes.rb
# routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope '/alfred' do
    resources :startups do
      member do
        patch 'favorite'
        patch 'unfavorite'
      end
    end

    get 'favorites', to: 'startups#favorites', as: 'favorites'

    root to: "startups#index", as: 'alfred_root'
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
# favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :startup
end

app/models/startup.rb
# startup.rb
class Startup < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favoriting_users, through: :favorites, source: :user

  attribute :favorite, :boolean, default: false

  validates :name, :homepage_url, :industry, :hq_location, :total_funding, :description, presence: true
end

app/models/user.rb
# user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :favorited_startups, through: :favorites, source: :startup
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :home_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def home_controller?
    self.class == HomeController
  end

  def after_sign_in_path_for(resource_or_scope)
    alfred_root_path # Always redirect to the All tab after sign in
  end

  def after_sign_out_path_for(resource_or_scope)
    startups_path # Redirect to a specific startup path after signing out
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :authenticate_user!, only: [:favorites, :favorite, :unfavorite]
  before_action :set_startup, only: %i[show edit update destroy favorite unfavorite]
  before_action :set_startups, only: %i[index show edit]

  def index
    @startups = filter_startups(params[:filter]).order(:name)
    @favorites = current_user.favorites.includes(:startup) if user_signed_in?
  end

  def favorites
    if user_signed_in?
      @startups = current_user.favorites.includes(:startup).map(&:startup)
      @favorites = current_user.favorites.includes(:startup)
    else
      @startups = []
    end
  end

  def show; end

  def new
    @startup = Startup.new
  end

  def edit; end

  def create
    @startup = Startup.new(startup_params)
    @startup.logo_url = 'no_logo.png' if @startup.logo_url.blank?

    respond_to do |format|
      if @startup.save
        format.html { redirect_to @startup, notice: "Startup was successfully created." }
        format.json { render :show, status: :created, location: @startup }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    favorite_status = params[:startup].delete(:favorite)
    @startup.logo_url = 'no_logo.png' if params[:startup][:logo_url].blank?

    respond_to do |format|
      if @startup.update(startup_params)
        if favorite_status.present?
          @startup.update(favorite: ActiveRecord::Type::Boolean.new.cast(favorite_status))
        end
        format.html { redirect_to @startup, notice: "Startup was successfully updated." }
        format.json { render :show, status: :ok, location: @startup }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @startup.destroy!

    respond_to do |format|
      format.html { redirect_to startups_url, notice: "Startup was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def favorite
    favorite = current_user.favorites.new(startup: @startup)

    respond_to do |format|
      if favorite.save
        format.json { render json: { status: 'favorited', count: current_user.favorites.count } }
      else
        format.json { render json: { status: 'error' }, status: :unprocessable_entity }
      end
    end
  end

  def unfavorite
    favorite = current_user.favorites.find_by(startup: @startup)

    respond_to do |format|
      if favorite&.destroy
        format.json { render json: { status: 'unfavorited', count: current_user.favorites.count } }
      else
        format.json { render json: { status: 'error' }, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_startup
    @startup = Startup.find(params[:id])
  end

  def set_startups
    @startups = Startup.all
  end

  def startup_params
    params.require(:startup).permit(:name, :homepage_url, :logo_url, :industry, :description, :hq_location, :total_funding, :comments, :funding_date, :last_funding, :round_name)
  end

  def filter_startups(filter)
    case filter
    when "YTD"
      year_start = Date.current.beginning_of_year
      Startup.where(funding_date: year_start..Time.current)
    when "Current Month"
      month_start = Date.current.beginning_of_month
      Startup.where(funding_date: month_start..Time.current)
    when "Current Quarter"
      quarter_start = Date.current.beginning_of_quarter
      Startup.where(funding_date: quarter_start..Time.current)
    when "Previous Quarter"
      quarter_start = (Date.current - 3.months).beginning_of_quarter
      quarter_end = quarter_start.end_of_quarter
      Startup.where(funding_date: quarter_start..quarter_end)
    when "Last 12 Months"
      one_year_ago = Date.current - 1.year
      Startup.where(funding_date: one_year_ago..Time.current)
    when "Previous Year"
      last_year = Date.current.last_year
      year_start = last_year.beginning_of_year
      year_end = last_year.end_of_year
      Startup.where(funding_date: year_start..year_end)
    else
      Startup.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_funding_date(date)
    day = date.day
    suffix = case day
             when 1, 21, 31 then 'st'
             when 2, 22 then 'nd'
             when 3, 23 then 'rd'
             else 'th'
             end
    day_with_suffix = "#{day}<sup>#{suffix}</sup>"
    "#{day_with_suffix} #{date.strftime('%b %y')}".html_safe
  end
end

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<% content_for :page_title, "Perpetual Growth. Empowering European Tech Founders" %>
<div class="typewriter-container" data-controller="hello">
  <p data-hello-target="output" class="typewriter-output"></p>
</div>
<div class="alfred-container-btn" data-controller="switch">
  <p data-switch-target="text" class="additional-text" style="display: none;">sourcing agent</p>
  <div class="form-check form-switch custom-switch" data-switch-target="switch" style="display: none;">
    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" data-url="/alfred" data-action="change->switch#toggleSwitch">
  </div>
</div>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title).presence || "Perpetual Growth | .alfred" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta property="og:title" content="Perpetual Growth. Empowering European Tech Founders">
  <meta property="og:description" content="Perpetual Growth empowers European Tech Founders to scale their businesses.">
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://www.perpetual-growth.com">
  <meta property="og:image" content="https://media.licdn.com/dms/image/D4D0BAQGsQKGD4MwU3g/company-logo_200_200/0/1704903103073/perpetualinvestors_logo?e=2147483647&v=beta&t=NtR3XlR_aWI53qrrWQ-IJMDxEqO387ZUOXtsT5cgR-M>"

  <script src="https://kit.fontawesome.com/39fe72d235.js" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="icon" type="image/png" href="/favicon.ico">
</head>

<body>
  <% unless controller_name == 'home' && action_name == 'index' %>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
  <% end %>

  <% unless controller_name == 'home' && action_name == 'index' || controller_name == 'sessions' || controller_name == 'registrations' || controller_name == 'passwords' %>
    <%= render "shared/navbar_wrapper" %>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- app/views/shared/_navbar.html.erb -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to ".alfred", startups_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown d-flex align-items-center">
            <a href="#" class="avatar" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "240601_AP_vLego.png", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item d-flex align-items-center">
            <i class="fa-regular fa-circle-user"></i>
            <%= link_to "Login", new_user_session_path, class: "nav-link login ms-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_wrapper.html.erb
<!-- app/views/shared/_navbar_wrapper.html.erb -->
<div class="navbar-wrapper" data-controller="filter">
  <div class="container-fluid">
    <h1>sourcing agent</h1>
    <% if user_signed_in? %>
      <%= current_user.first_name %>,
      <% if params[:action] == 'favorites' %>
        you have <%= @favorites&.count || 0 %> favorite investments.
      <% else %>
        there are <%= @startups&.count || 0 %> investments for you to watch.
      <% end %>
    <% else %>
      There are <%= @startups&.count || 0 %> investments for you to watch.
    <% end %>
    <br>
    <nav class="custom-navbar d-flex justify-content-between">
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link <%= 'active' if params[:controller] == 'startups' && params[:action] == 'index' %>" id="nav-all-tab" href="<%= alfred_root_path %>" aria-controls="nav-all" aria-selected="true" data-filter-target="allTab">All</a>
        <a class="nav-item nav-link <%= 'active' if params[:controller] == 'startups' && params[:action] == 'favorites' %>" id="nav-favorites-tab" href="<%= favorites_path %>" aria-controls="nav-favorites" aria-selected="false" data-filter-target="favoritesTab">Favorites</a>
      </div>
      <% if user_signed_in? %>
        <div class="dropdown">
          <span class="fa-icon"><i class="fa-solid fa-sliders"></i></span>
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false" data-filter-target="dropdownButton">
            All dates
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
            <li><%= link_to 'Current Month', alfred_root_path(filter: 'Current Month'), class: 'dropdown-item', data: { filter_target: "dropdownItem", filter: 'Current Month' } %></li>
            <li><%= link_to 'Current Quarter', alfred_root_path(filter: 'Current Quarter'), class: 'dropdown-item', data: { filter_target: "dropdownItem", filter: 'Current Quarter' } %></li>
            <li><%= link_to 'Previous Quarter', alfred_root_path(filter: 'Previous Quarter'), class: 'dropdown-item', data: { filter_target: "dropdownItem", filter: 'Previous Quarter' } %></li>
            <li><%= link_to 'YTD', alfred_root_path(filter: 'YTD'), class: 'dropdown-item', data: { filter_target: "dropdownItem", filter: 'YTD' } %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Last 12 Months', alfred_root_path(filter: 'Last 12 Months'), class: 'dropdown-item', data: { filter_target: "dropdownItem", filter: 'Last 12 Months' } %></li>
            <li><%= link_to 'Previous Year', alfred_root_path(filter: 'Previous Year'), class: 'dropdown-item', data: { filter_target: "dropdownItem", filter: 'Previous Year' } %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'All dates', alfred_root_path(filter: 'All dates'), class: 'dropdown-item', data: { filter_target: "dropdownItem", filter: 'All dates' } %></li>
          </ul>
        </div>
      <% end %>
    </nav>
  </div>
</div>

app/views/shared/_old_subpage.html.erb
<!-- app/views/shared/_subpage.html.erb -->
  <div class="navbar-wrapper">
  <h1>sourcing agent</h1>
   <% if user_signed_in? %>
    <%= current_user.first_name %>,
    <% if params[:action] == 'favorites' %>
      you have <%= @favorites.count %> favorite investments.
      <% else %>
      there are <%= @startups.count %> investments for you to watch.
    <% end %>
    <% else %>
      There are <%= @startups.count %> investments for you to watch.
    <% end %>
  </p>
  <br>
  <nav class="custom-navbar">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link <%= 'active' if params[:controller] == 'startups' && params[:action] == 'index' %>" id="nav-all-tab" href="<%= alfred_root_path %>" aria-controls="nav-all" aria-selected="true">All</a>
      <a class="nav-item nav-link <%= 'active' if params[:controller] == 'startups' && params[:action] == 'favorites' %>" id="nav-favorites-tab" href="<%= favorites_path %>" aria-controls="nav-favorites" aria-selected="false">Favorites</a>
    </div>
  </nav>

  <div class="tab-content cards-container" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-<%= params[:action] == 'favorites' ? 'favorites' : 'all' %>" role="tabpanel" aria-labelledby="nav-<%= params[:action] == 'favorites' ? 'favorites' : 'all' %>-tab">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_subpage.html.erb
<!-- app/views/shared/_subpage.html.erb -->
  <div class="navbar-wrapper">
  <h1>sourcing agent</h1>
   <% if user_signed_in? %>
    <%= current_user.first_name %>,
    <% if params[:action] == 'favorites' %>
      you have <%= @favorites.count %> favorite investments.
      <% else %>
      there are <%= @startups.count %> investments for you to watch.
    <% end %>
    <% else %>
      There are <%= @startups.count %> investments for you to watch.
    <% end %>
  </p>
  <br>
  <nav class="custom-navbar">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link <%= 'active' if params[:controller] == 'startups' && params[:action] == 'index' %>" id="nav-all-tab" href="<%= alfred_root_path %>" aria-controls="nav-all" aria-selected="true">All</a>
      <a class="nav-item nav-link <%= 'active' if params[:controller] == 'startups' && params[:action] == 'favorites' %>" id="nav-favorites-tab" href="<%= favorites_path %>" aria-controls="nav-favorites" aria-selected="false">Favorites</a>
    </div>
  </nav>

  <div class="tab-content cards-container" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-<%= params[:action] == 'favorites' ? 'favorites' : 'all' %>" role="tabpanel" aria-labelledby="nav-<%= params[:action] == 'favorites' ? 'favorites' : 'all' %>-tab">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/startups/_form.html.erb
<!-- app/views/startups/_form.html.erb -->
<%= simple_form_for(@startup) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.input :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :logo_url, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :homepage_url, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :description, as: :text, input_html: { class: 'form-control', rows: 5 } %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.input :industry, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :hq_location, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :last_funding, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :comments, as: :text, input_html: { class: 'form-control', rows: 5 } %> <!-- Ensure text area with proper rows -->
      </div>

    </div>
  </div>

  <div class="form-actions d-flex justify-content-start">
    <%= f.button :submit, "Update startup", class: 'btn btn-primary btn-custom' %>
  </div>
<% end %>

<div class="card-text">
  <%= link_to "Show this startup", @startup %> |
  <%= link_to "Back to startups", startups_path %>
</div>

app/views/startups/_startup.html.erb
<!-- _startup.html.erb -->
<div class="d-flex justify-content-center mt-3">
  <div class="container w-100">
    <div class="row align-items-stretch">
      <div class="col-md-4 border p-3 custom-card-show d-flex flex-column me-md-3"> <!-- Added margin-end class -->
        <h5 class="card-title"><b>Details</b></h5>
        <ul class="list-group mt-3">
          <li class="list-group-item"><b>Name:</b> <%= @startup.name %></li>
          <li class="list-group-item"><b>Industry:</b> <%= @startup.industry %></li>
          <li class="list-group-item"><b>HQ Location:</b> <%= @startup.hq_location %></li>
          <li class="list-group-item"><b>Website:</b> <a href="<%= @startup.homepage_url %>" target="_blank"><%= @startup.homepage_url %></a></li>
        </ul>
      </div>
      <div class="col-md-8 border p-3 custom-card-show d-flex flex-column"> <!-- Changed col-md-8 back -->
        <h5 class="card-title"><b>Description</b></h5>
        <p class="card-text mt-3"><%= @startup.description %></p>
      </div>
    </div>
    <div class="row align-items-stretch mt-3">
      <div class="col-12 border p-3 custom-card-show d-flex flex-column custom-card-comments">
        <h5 class="card-title"><b>Comments</b></h5>
        <p class="card-text"><%= simple_format(@startup.comments) %></p>
    </div>
</div>
  </div>
  </div>
</div>

app/views/startups/_startups_list.html.erb
<% startups.each do |startup| %>
  <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 mb-2">
    <div class="card-wrapper">
      <div class="card custom-card position-relative h-100">
        <% if user_signed_in? %>
          <%= link_to startup_path(startup), class: "card-link" do %>
            <div class="card-img-top-container">
              <%= image_tag startup.logo_url, class: "card-img-top img-fluid", alt: "Startup logo" %>
            </div>
            <div class="card-body">
              <p class="card-text">
                <b class="startup-name"><%= startup.name %></b><br>
                <span class="startup-industry"><%= startup.industry %></span><br>
                <span class="location-date">
                  <i class="fa-solid fa-location-dot"></i> <%= startup.hq_location %>
                  <span class="funding-date"><%= formatted_funding_date(startup.funding_date) %></span>
                </span>
              </p>
            </div>
            <div class="card-footer custom-footer">
              <b class="funding-info"><%= startup.round_name %>, $<%= startup.last_funding %>mn</b>
            </div>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path, class: "card-link" do %>
            <div class="card-img-top-container">
              <%= image_tag startup.logo_url, class: "card-img-top img-fluid", alt: "Startup logo" %>
            </div>
            <div class="card-body">
              <p class="card-text">
                <b class="startup-name"><%= startup.name %></b><br>
                <span class="startup-industry"><%= startup.industry %></span><br>
                <span class="location-date">
                  <i class="fa-solid fa-location-dot"></i> <%= startup.hq_location %>
                  <span class="funding-date"><%= formatted_funding_date(startup.funding_date) %></span>
                </span>
              </p>
            </div>
            <div class="card-footer custom-footer">
              <b class="funding-info"><%= startup.round_name %>, $<%= startup.last_funding %>mn</b>
            </div>
          <% end %>
        <% end %>
        <% if user_signed_in? %>
          <% if current_user.favorites.exists?(startup: startup) %>
            <i class="fa-solid fa-heart heart-icon ml-2 favorite-toggle" data-controller="favorite" data-action="click->favorite#toggle" data-startup-id="<%= startup.id %>"></i>
          <% else %>
            <i class="fa-regular fa-heart heart-icon ml-2 favorite-toggle" data-controller="favorite" data-action="click->favorite#toggle" data-startup-id="<%= startup.id %>"></i>
          <% end %>
          <a href="<%= startup.cb_link %>" target="_blank">
            <%= image_tag 'crunchbase_logo.png', alt: 'Crunchbase Logo', class: 'crunchbase-logo ml-2' %>
          </a>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/startups/edit.html.erb
<!-- app/views/startups/edit.html.erb -->
<div class="container mt-5" data-controller="filter">
  <div class="edit-content-container">
  <%= render "form", startup: @startup %>
  <br>
  </div>
</div>

app/views/startups/favorites.html.erb
<!-- app/views/startups/favorites.html.erb -->
<div class="content-container">
  <div class="container mt-5">
    <div class="row cards-row">
      <% @startups.each do |startup| %>
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 mb-2">
          <div class="card-wrapper">
            <div class="card custom-card position-relative h-100">
              <% if user_signed_in? %>
                <%= link_to startup_path(startup), class: "card-link" do %>
                  <div class="card-img-top-container">
                    <%= image_tag startup.logo_url, class: "card-img-top img-fluid", alt: "Startup logo" %>
                  </div>
                  <div class="card-body">
                    <p class="card-text">
                      <b class="startup-name"><%= startup.name %></b><br>
                      <span class="startup-industry"><%= startup.industry %></span><br>
                      <span class="location-date">
                        <i class="fa-solid fa-location-dot"></i> <%= startup.hq_location %>
                        <span class="funding-date"><%= formatted_funding_date(startup.funding_date) %></span>
                      </span>
                    </p>
                  </div>
                  <div class="card-footer custom-footer">
                    <b class="funding-info"><%= startup.round_name %>, $<%= startup.last_funding %>mn</b>
                  </div>
                <% end %>
              <% end %>
              <% if user_signed_in? %>
                <% if current_user.favorites.exists?(startup: startup) %>
                  <i class="fa-solid fa-heart heart-icon ml-2 favorite-toggle disabled" data-controller="favorite" data-action="click->favorite#toggle" data-startup-id="<%= startup.id %>" data-favorites-tab="true"></i>
                <% else %>
                  <i class="fa-regular fa-heart heart-icon ml-2 favorite-toggle disabled" data-controller="favorite" data-action="click->favorite#toggle" data-startup-id="<%= startup.id %>" data-favorites-tab="true"></i>
                <% end %>
                <a href="<%= startup.cb_link %>" target="_blank">
                  <%= image_tag 'crunchbase_logo.png', alt: 'Crunchbase Logo', class: 'crunchbase-logo ml-2' %>
                </a>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/startups/index.html.erb
<!-- app/views/startups/index.html.erb -->
<div class="content-container">
  <div class="container mt-5">
    <% if @startups.empty? %>
       No fundraisings in the selected period.
      </div>
    <% else %>
      <div id="startups-container" class="row cards-row">
        <%= render partial: 'startups/startups_list', locals: { startups: @startups } %>
      </div>
    <% end %>
  </div>
</div>

app/views/startups/new.html.erb
<div class="container" style="margin-top: 70px;">
  <h1>New Startup</h1>

<%= render "form", startup: @startup %>

<br>
</div>

app/views/startups/show.html.erb
<!-- app/views/startups/show.html.erb -->
<div class="show-content-container">
  <div class="container mt-5">
    <%= render @startup %>
    <div class="mt-3 buttons-container">
      <%= link_to "Edit this startup", edit_startup_path(@startup) %> |
      <%= link_to "Back to startups", startups_path %>
    </div>
  </div>
</div>

app/views/startups/temp_code_snippets.html.erb
<!-- img link-->
<a href="<%= startup.homepage_url %>" target="_blank">
              <div class="card-img-top-container">
                <%= image_tag startup.logo_url, class: "card-img-top img-fluid", alt: "Startup logo" %>
              </div>
</a>
<!-- img link-->

<!-- Info button -->

                <a href="<%= startup_path(startup) %>" class="btn btn-primary btn-custom">
                  <i class="fas fa-info-circle"></i><span class="icon-text">More Info</span>
                </a>

<!-- Info button -->

<%= render 'shared/subpage' %>

Startup
<div class="row align-items-center">
  <div class="col-md-8 d-flex align-items-center">
    <h1><%= @startup.name %></h1>
    <% if user_signed_in? %>
      <% if current_user.favorites.exists?(startup: @startup) %>
        <i class="fa-solid fa-heart p-3"></i>
      <% else %>
        <i class="fa-regular fa-heart p-3"></i>
      <% end %>
    <% else %>
      <i class="fa-regular fa-heart p-3"></i>
    <% end %>
  </div>
  <div class="col-md-4 text-md-right text-center">
    <%= image_tag @startup.logo_url, class: "img-fluid startup-logo", alt: "Startup Logo" %>
  </div>
</div>


<div class="alfred-container-btn" data-controller="button">
  <p data-button-target="text" class="additional-text" style="display: none;">sourcing agent </p>
  <a href="/alfred" target="_blank" data-button-target="button" class="explore-btn" style="display: none;">
    Explore
  </a>
 </div>